import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ClientOnly from "./components/ClientOnly/ClientOnly";
import ToasterProvider from "@/providers/toast-provider";
import AuthProvider from "./context/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gym Management System",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <ToasterProvider />
          <AuthProvider>{children}</AuthProvider>
        </ClientOnly>
      </body>
    </html>
  );
}
